In [1]:
import numpy as np

hidden_num=1;
datatype=np.float32

mm=0.3
epoch_size=4
epoch_num=100
lr=0.5

inputs=np.matrix([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]],dtype=datatype)
true_out=np.matrix(np.reshape([0.0,1.0,1.0,0.0],(epoch_size,-1)))
print(inputs.shape)
print('true_out:',true_out)

def hidden_layer(inputs,units,activ=None,train=0,wg=None):
    if train==0:
        weights=np.matrix(np.random.randn(inputs.shape[1],units))
    else:
        weights=wg
    print(weights)
    
    bias=np.zeros(units)
    res_weights=inputs*weights+bias
    print(res_weights)
    
    if activ!=None: 
        result=activ(res_weights)
    print(result)
    
    return result,weights,bias
   
def logist(x):
    y=1/(1+np.exp(-x))
    return y

sample=0

for i in range(epoch_num):
    sample=sample+1
    h1,weights1,bias1=hidden_layer(inputs[sample%4],2,logist)
    output,weights_out,bias_out=hidden_layer(h1,1,logist)
    print('%d ouput:'%(sample),output)
    #print(true_out-output)
    #print(1-output)

(4, 2)
true_out: [[0.]
 [1.]
 [1.]
 [0.]]
[[-0.91464185 -0.40305901]
 [ 0.44768889 -0.31531683]]
[[ 0.44768889 -0.31531683]]
[[0.61008961 0.4218175 ]]
[[ 0.44785773]
 [-0.13551348]]
[[0.21607139]]
[[0.55380866]]
1 ouput: [[0.55380866]]
[[-0.95032422  1.02152507]
 [-0.51026381 -0.7085524 ]]
[[-0.95032422  1.02152507]]
[[0.27881962 0.73526956]]
[[-1.41629288]
 [ 0.95606962]]
[[0.30807864]]
[[0.57641621]]
2 ouput: [[0.57641621]]
[[-0.62610208 -1.60264227]
 [-1.95582221  0.30535148]]
[[-2.58192429 -1.2972908 ]]
[[0.07031084 0.21462132]]
[[-0.50828454]
 [ 1.98828089]]
[[0.39098956]]
[[0.59652089]]
3 ouput: [[0.59652089]]
[[-0.86896097  0.2715398 ]
 [ 0.71802717 -1.05802535]]
[[0. 0.]]
[[0.5 0.5]]
[[0.68436481]
 [0.80824957]]
[[0.74630719]]
[[0.67837352]]
4 ouput: [[0.67837352]]
[[-0.11825443  0.02957359]
 [-0.41819539 -0.15302983]]
[[-0.41819539 -0.15302983]]
[[0.39694866 0.46181703]]
[[-0.05137266]
 [-1.47761668]]
[[-0.70278085]]
[[0.33119597]]
5 ouput: [[0.33119597]]
[[ 0.13788505 -0.8435

In [2]:
    E_out=np.array(output)*np.array((1-output))*np.array((true_out[0]-output))
    #print(E_out)

In [3]:
    #print(h1)
    #print(1-h1)
    output_T=output.T
   # print(output_T)
  #  print('weights_out:',weights_out)
  #  print(weights_out*output_T)
    h1_entroy=np.array(h1)*np.array(1-h1)
    E_h1=np.array(h1_entroy)*np.array(((weights_out*output_T).T))
   # print(E_h1)

In [4]:
    weights_out=weights_out+lr*np.multiply(output,E_out)
   # print(lr*np.multiply(output,E_out))
   # print(weights_out)

print(weights1)
print(lr*np.multiply(h1,E_h1))

In [5]:
    bias_out=weights_out+lr*E_out

In [6]:
   # print(weights1) 
  #  print(lr*np.multiply(h1,E_h1))

In [7]:
    weights1=weights1+lr*np.multiply(h1,E_h1)
   # print(weights1)

    bias1=weights1+lr*E_h1

In [8]:
    sample=sample+1
    h1,weights1,bias1=hidden_layer(inputs[sample%4],2,logist,train=1,wg=weights1)
    output,weights_out,bias_out=hidden_layer(h1,1,logist,train=1,wg=weights_out)
    print('%d output:'%(sample),output)

[[-0.63787777  2.21343874]
 [-1.01450686  0.02702794]]
[[-1.01450686  0.02702794]]
[[0.26609878 0.50675657]]
[[-1.42749672]
 [-0.28732851]]
[[-0.52546075]]
[[0.37157622]]
101 output: [[0.37157622]]
